import { icon, Layout, PageHero, SectionHead } from './shared'
import type { UserSession } from '../types'

export function About({ user }: { user?: UserSession }) {
  return <Layout user={user} title="من نحن | مؤسسة الدكتور عمر هشام">
    <PageHero kicker="من نحن" title={'من الفقد وُلد نورٌ،<br/><em>ومن الحلم وُلد أثر.</em>'} text="حكاية إنسان لم يتوقف حلمه برحيله، بل صار بابًا للخير يدخل منه الجميع." />
    <section class="about-memorial section-pad"><div class="memorial-image reveal"><img src="/static/omar-portrait.jpg" alt="الدكتور عمر هشام" /><div class="image-prayer">رحمه الله رحمةً واسعة</div></div><article class="memorial-text reveal"><p class="eyebrow"><span></span>صدقة جارية</p><h2>كان عمر يحلمُ بالشفاء،<br />فنحن نُكمل الحلم.</h2><p>في ذاكرة كل من عرفه، بقي الدكتور عمر هشام شابًا طموحًا، بشوشًا، يحمل حلم الطب ورسالة الرحمة. وحين اختاره الله، قرر والده المهندس هشام صبري أن يتحوّل الحزن إلى يدٍ تمتد لكل محتاج.</p><blockquote>«ليحمل اسمُه رسالة نشر الخير والرحمة والإحسان بين الناس.»</blockquote></article></section>
    <section class="sacred-section"><div class="sacred-pattern"></div><p class="eyebrow">دعاءٌ يصل إلى السماء</p><h2>اللهم اغفر له وارحمه، وعافه واعف عنه،<br />وأكرم نزله، ووسّع مدخله.</h2><div class="fatiha"><h3>الفاتحة</h3><p>بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ <span class="ayah-number">١</span><br />الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ <span class="ayah-number">٢</span> الرَّحْمَنِ الرَّحِيمِ <span class="ayah-number">٣</span> مَالِكِ يَوْمِ الدِّينِ <span class="ayah-number">٤</span> إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ <span class="ayah-number">٥</span> اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ <span class="ayah-number">٦</span> صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ <span class="ayah-number">٧</span></p></div><button class="light-btn toast-trigger" data-message="جزاك الله خيرًا، تقبّل الله دعاءك ورحم حبيبنا وأسكنه فسيح جناته">قرأتُ الفاتحة وأهديتُه الرحمة {icon('fa-heart')}</button></section>
    <section class="values section-pad"><SectionHead kicker="ما نؤمن به" title={'قيمٌ لا نكتبها على الجدران،<br/><em>بل نمارسها كل يوم.</em>'} /><div class="value-grid">{[['الإخلاص', 'كل ما نقدمه خالصًا لوجه الله.'], ['الشفافية', 'وضوحٌ وأمانة في كل خطوة.'], ['المسؤولية', 'أثر حقيقي ومستدام في المجتمع.'], ['الرحمة', 'نقف بجوار المحتاج بلطف وكرامة.'], ['الشراكة', 'معًا يصبح أثر الخير أكبر.']].map((v, i) => <article class="value-card reveal"><span>0{i + 1}</span><h3>{v[0]}</h3><p>{v[1]}</p></article>)}</div></section>
  </Layout>
}
